mysql5.7:
  image: mysql:5.7
  container_name: mysql5.7
  ports:
    - 3306:3306
  environment:
    - MYSQL_DATABASE=test
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - ./mysql5.7/conf.d:/etc/mysql/conf.d
